debug:
  false

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alfred?characterEncoding=utf8&useSSL=false&tinyInt1isBit=false&autoReconnect=true
    username: root
    password: root

#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password:       # 密码（默认为空）

swagger:
  enabled: true